input_image1 = rgb2gray(imread('edgedetected.jpg'));
input_image2 = imread('houghlines3.jpg');
%input_image2 = rgb2gray(imread('./CV Project/switch.jpg'));
maxPeaks = 1; 
fillgap = 500; 
minline = 7; 
binary_image1 = edge(input_image1,'canny');
binary_image2 = edge(input_image2,'canny');
[H1,T1,R1] = hough(binary_image1);
[H2,T2,R2] = hough(binary_image2);
threshPeaks1 = ceil(0.3*max(H1(:)));
threshPeaks2 = ceil(0.3*max(H2(:))); 
P1  = houghpeaks(H1, maxPeaks, 'threshold', threshPeaks1);   
P2  = houghpeaks(H2, maxPeaks, 'threshold', threshPeaks2); 
hlines1 = houghlines(binary_image1, T1, R1, P1, 'FillGap', fillgap, 'MinLength', minline);
hlines2 = houghlines(binary_image2, T2, R2, P2, 'FillGap', fillgap, 'MinLength', minline);
h_line1 = hlines1(1);
h_line2 = hlines2(1);
X1 = [h_line1.point1(1),h_line1.point1(2);h_line1.point2(1),h_line1.point2(2)];
X2 = [h_line2.point1(1),h_line2.point1(2);h_line2.point2(1),h_line2.point2(2)];
height = pdist(X1,'euclidean');
width = pdist(X2,'euclidean');
figure,imshow(input_image1);
hold on;
hline1 = plot([h_line1.point1(1) h_line1.point2(1)],[h_line1.point1(2) h_line1.point2(2)],'w','LineWidth',4);
hline1.Color = 'red';
hline3.Color = 'blue';
title(['This height of wall is:', num2str(height)]);
figure,imshow(input_image2);
hold on;
hline2 = plot([h_line2.point1(1) h_line2.point2(1)],[h_line2.point1(2) h_line2.point2(2)],'w','LineWidth',4);
hline2.Color = 'Green';
title(['This width of wall is:', num2str(width)]);
diminpixels = strjoin({'in pixels room height:',num2str(height),'and width:',num2str(width)},' ');
disp([diminpixels]);
reference_height = 5.433071;
reference_width = 3.58268;
switchrefinches = strjoin({'in inches height:',num2str(reference_height),'and width:',num2str(reference_width)},' ');
disp([switchrefinches]);
switch_height = 59;
switch_width = 40;
switchrefinpixels = strjoin({'in pixels height:',num2str(switch_height),'and width:',num2str(switch_width)},' ');
disp([switchrefinpixels]);
height_observed = (height * reference_height)/switch_height;
width_observed = (width* height_observed)/height;
heightandwidthobserved = strjoin({'in inches observed room height:',num2str(height_observed),'and width:',num2str(width_observed)},' ');
disp([heightandwidthobserved]);
height_real = 98.897638;
width_real = 157.24409;
heightandwidthreal = strjoin({'in inches real room height:',num2str(height_real),'and width:',num2str(width_real)},' ');
disp([heightandwidthreal]);
height_error_rate = (abs(height_observed - height_real)/height_real)*100;
width_error_rate = (abs(width_observed - width_real)/width_real)*100;
disp([strjoin({'error in % for room height:',num2str(height_error_rate),'and width:',num2str(width_error_rate)},' ');])